name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive crate version (strip leading 'v')
        id: version
        shell: bash
        run: |
          RAW_TAG="${GITHUB_REF_NAME}"
          CLEAN_TAG="${RAW_TAG#v}"
          echo "version=${CLEAN_TAG}" >> "$GITHUB_OUTPUT"

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            # libsodium-rs ${{ github.ref_name }}

            ## Changes
            ${{ steps.changelog.outputs.changelog }}

            ## Installation

            ```toml
            [dependencies]
            libsodium-rs = "${{ steps.version.outputs.version }}"
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
