name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            # libsodium-rs ${{ github.ref_name }}
            
            ## Changes
            ${{ steps.changelog.outputs.changelog }}
            
            ## Installation
            
            ```toml
            [dependencies]
            libsodium-rs = "${{ github.ref_name }}"
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
